
-- INSERT SAMPLE DATA

-- USERS
INSERT INTO users (full_name,email,phone) VALUES
('Ali Khan','ali@email.com','1111111111'),
('Sara Ahmed','sara@email.com','2222222222'),
('John Smith','john@email.com','3333333333');


-- DRIVERS
INSERT INTO drivers (full_name,license_number,phone,status) VALUES
('David Miller','DL12345','4444444444','available'),
('Michael Brown','DL56789','5555555555','available');


-- VEHICLES
INSERT INTO vehicles (driver_id,vehicle_model,license_plate,capacity) VALUES
(1,'Toyota Prius','ABC123',4),
(2,'Honda Civic','XYZ789',4);


-- TRIPS
INSERT INTO trips
(user_id,driver_id,pickup_location,dropoff_location,trip_status,fare_amount)
VALUES
(1,1,'Airport','City Center','completed',25.50),
(2,2,'Mall','University','completed',18.00);


-- PAYMENTS
INSERT INTO payments
(trip_id,payment_method,payment_status,amount)
VALUES
(1,'card','completed',25.50),
(2,'cash','completed',18.00);


-- RATINGS
INSERT INTO ratings
(trip_id,user_id,driver_id,rating,review)
VALUES
(1,1,1,5,'Great ride!'),
(2,2,2,4,'Smooth trip');




-- BULK GENERATED RECORDS

INSERT INTO users (full_name,email,phone)
SELECT
 CONCAT('User_',n),
 CONCAT('user',n,'@mail.com'),
 CONCAT('900000',LPAD(n,4,'0'))
FROM (
 SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35
 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45
 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55
 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60
 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65
 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70
 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75
 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80
 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85
 UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90
 UNION SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95
 UNION SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100
) numbers;








INSERT INTO drivers (full_name,license_number,phone,status)
SELECT
 CONCAT('Driver_',n),
 CONCAT('LIC',1000+n),
 CONCAT('800000',LPAD(n,4,'0')),
 'available'
FROM (
 SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35
 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45
 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55
 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60
 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65
 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70
 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75
 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80
 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85
 UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90
 UNION SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95
 UNION SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100
) numbers;


INSERT INTO vehicles (driver_id,vehicle_model,license_plate,capacity)
SELECT
 driver_id,
 'Toyota Prius',
 CONCAT('CAR',driver_id),
 4
FROM drivers;




INSERT INTO trips
(user_id,driver_id,pickup_location,dropoff_location,trip_status,fare_amount)
SELECT
 FLOOR(1 + RAND()*100),
 FLOOR(1 + RAND()*100),
 'Location_A',
 'Location_B',
 'completed',
 ROUND(10 + RAND()*40,2)
FROM users
LIMIT 100;



INSERT INTO payments
(trip_id,payment_method,payment_status,amount)
SELECT
 trip_id,
 'card',
 'completed',
 fare_amount
FROM trips;



INSERT INTO ratings
(trip_id,user_id,driver_id,rating,review)
SELECT
 trip_id,
 user_id,
 driver_id,
 FLOOR(1 + RAND()*5),
 'Good ride experience'
FROM trips
LIMIT 100;



SELECT COUNT(*) FROM users;
SELECT COUNT(*) FROM drivers;
SELECT COUNT(*) FROM vehicles;
SELECT COUNT(*) FROM trips;
SELECT COUNT(*) FROM payments;
SELECT COUNT(*) FROM ratings;